kind: Service
apiVersion: v1
metadata:
  name: japan-tour
  labels:
    app: japan-tour
spec:
  selector:
    app: japan-tour
  ports:
  - port: 9080
    name: http
---

kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: japan-tour
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: japan-tour
    spec:
      containers:
      - name: japan-tour
        image: sdaschner/japan-tour:1
        ports:
        - containerPort: 9080
        imagePullPolicy: Always
      restartPolicy: Always
---

kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: japan-tour
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /japan-tour
        backend:
          serviceName: japan-tour
          servicePort: 9080
---
